{
  "tagFormat": "v${version}",
  "plugins": [
    ["@semantic-release/commit-analyzer", { "preset": "angular" }],
    "@semantic-release/release-notes-generator",
    ["@semantic-release/changelog", { "preset": "angular" }],
    ["@semantic-release/npm", { "npmPublish": false, "pkgRoot": "com.thelegends.unity.utils/Packages/com.thelegends.unity.utils" }],
    ["@semantic-release/git", {
      "assets": ["com.thelegends.unity.utils/Packages/com.thelegends.unity.utils/package.json", "CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }],
    "@semantic-release/github"
  ]
}
